version: "3"

networks:
    costrad-net:
        driver: bridge

services:

    costrad:
        image: mysql
        restart: always
        tty: true
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-database}
            MYSQL_USER: ${MYSQL_USER:-database}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Password}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootPassword}
            SERVICE_TAGS: dev
            SERVICE_NAME: costraddb
        volumes:
            - ./db_backup:/var/lib/mysql
        networks:
            - costrad-net

    # redis
    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - costrad-net

    # adminer
    adminer:
        image: adminer
        restart: always
        depends_on:
            - costrad
        networks:
            - costrad-net
        ports:
            - 8005:8080
        environment:
            ADMINER_DESIGN: "pepa-linha"
            ADMINER_DEFAULT_SERVER: mysql

    # redis commander
    redis-commander:
        networks:
            - costrad-net
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 8004:8081

